name: compile test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "compile"
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/run-vcpkg@v11
      - name: Build
        run: |
          cmake -G "NMake Makefiles" .
          cd /build
          cmake --build .
  
